// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1EMmjCq5MtfZMguTfEBN3DBa8ix2PDKk',
    appId: '1:48139991310:web:bab15f19e7b210420cbf5f',
    messagingSenderId: '48139991310',
    projectId: 'panaderia-liz',
    authDomain: 'panaderia-liz.firebaseapp.com',
    storageBucket: 'panaderia-liz.firebasestorage.app',
    measurementId: 'G-QQ71VNZMST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCET_LacXPw-vlqO8WR_jlgBbOuJ6daZWU',
    appId: '1:48139991310:android:65edb57d8aebad3f0cbf5f',
    messagingSenderId: '48139991310',
    projectId: 'panaderia-liz',
    storageBucket: 'panaderia-liz.firebasestorage.app',
  );
}
